### ISSUE TITLE
indication of different helm chart repositories

### ISSUE THREAD

**Issue by pniederlag** [samsung-cnct/jenkins-operator#27]
README mentions two different sources for installing jenkins-operator via helm chart.

On incubator/helm the most recent chart version is 0.1.12
On charts.cnct.io the most recent chart version is 0.3.0

Would be nice if these chart repos would be in sync or the purpose of having two different repositories could be explained.

Thx for any feedback/input

**Comment by maratoid** [comment]
Hello!
Thanks for you interest. The reason chart versions are different in these two repositories is because the turnaround time for getting something merged into https://github.com/helm/charts is very very very long.
Last PR I submitted was closed due to age. 
I'll give it another shot today.

**Comment by pniederlag** [comment]
thx for looking into it. my suggestion, as you indicate the jenkins-operator is currently alpha, we are likely to see changes, updates and incompatibilities. So how about just sticking with your own chart repository, and adding a note in the README that the chart in the incubator is likely to lag behind?
