### ISSUE TITLE
trouble with samples

### ISSUE THREAD

**Issue by pniederlag** [samsung-cnct/jenkins-operator#29]
I had to specify storage requirements as "5Gi", as "5G" was for some reason causing errors

https://github.com/samsung-cnct/jenkins-operator/blob/29219d40aea2ef611d272936d7796d2d717aa869/samples/jenkins_v1alpha2_jenkinsinstance.yaml#L50

remotingCLI was removed from jenkins and also causes errors

https://github.com/samsung-cnct/jenkins-operator/blob/29219d40aea2ef611d272936d7796d2d717aa869/samples/configmap.yaml#L68

do you have any policy regarding compliance with kubernetes and or jenkins versions?

**Comment by maratoid** [comment]
As far as kubernetes versions, for now we will try to keep up with what is provided by kubebuilder. 
Looks like v2.0.0 was released abut 8 days ago, so I'll create an issue to update to that.

You get to specify your own Jenkins version with 

```
spec:
    image: "jenkins/jenkins:lts"
```

As long as that jenkins and latest configuration-as-code plugin are compatible. Come to thing of it, its probably a good idea to expose overriding https://github.com/samsung-cnct/jenkins-operator/blob/master/pkg/configdata/environment/required-plugins versions. I'll add an issue.

We've also been playing around with adding https://jenkins.io/projects/evergreen/ support

**Comment by maratoid** [comment]
https://github.com/samsung-cnct/jenkins-operator/pull/32
