### ISSUE TITLE
json: invalid number literal "1.7.3" / Issue with value for build-blocker-plugin version value

### ISSUE THREAD

**Issue by sabur7** [samsung-cnct/jenkins-operator#33]
I am seeing this error constantly in the logs for the operator pod. It seems to be complaining of the string "1.7.3" in my jenkinsinstance yaml file. This error is repeated constantly.

ERROR:
E1010 19:04:52.310718       1 jenkinsinstance_controller.go:324] Error updating JenkinsInstance default/jenkinsinstance-team1: json: invalid number literal "1.7.3"
E1010 19:06:20.492016       1 jenkinsinstance_controller.go:324] Error updating JenkinsInstance default/jenkinsinstance-team1: json: invalid number literal "1.7.2"

The issue appears to only affect the value for the version of the 'build-blocker-plugin'
No matter what I change the value to, or if I change the double quotes to single quotes or no quotes, it still complains with that error in the Operator log.

**Comment by notjames** [comment]
For the sake of interest, please try "v1.7.3" if you haven't already.
